### ISSUE TITLE
use the x86 nUnit runner to execute x86 assemblies

### ISSUE THREAD

**Issue by Ang3lFir3** [codereflection/Giles#1]
By default Giles does not inspect the assembly it is trying to load for platform information. Attempting to execute code compiled to x86 will cause the default nUnit runner to get mad.

giving us the good ole:

Could not load file or assembly 'GildedRose.Console, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by codereflection** [comment]
We might be able to resolve this issue by inspecting the assemblies and running the x86 NUnit console runner.

Alternatively, this issue may go away when Giles switches from using the console runners to using each framework's runner lib directly.

**Comment by SaintGimp** [comment]
Now that you're loading the framework runner libs directly, the only possible way to solve this problem is to provide two binaries: Giles.exe and Giles-x86.exe, where the first is built for AnyCPU and the second is built for x86.  The first can be used when running x86 or AnyCPU test binaries on a 32-bit OS or when running x64 or AnyCPU test binaries on a 64-bit OS, and the second is used when running x86 test binaries on a 64-bit OS.  Technically you'd also want a Giles-x64.exe for running x64 test binaries on a 32-bit OS but no one ever does that.  See e.g. the different flavors of MSpec.exe that's provided with Machine.Specifications.

**Comment by codereflection** [comment]
Yeah, that's pretty frustrating.  Trying to come up with a clever way of detecting the bitness and launching the correct runner.

**Comment by codereflection** [comment]
Try out v0.1.1.2 of Giles to see if you have the same issue. A Giles-x86 version is now included for your thunking pleasure.

**Comment by codereflection** [comment]
old issue, x86 runner now solves this problem.
