### ISSUE TITLE
Can Giles not eat Ctrl-C for breakfast?

### ISSUE THREAD

**Issue by cbilson** [codereflection/Giles#4]
It was a little disorienting when it didn't exit after I hit Ctrl-C. Obviously this is intentional, but I was wondering what the reasoning behind this was.

**Comment by codereflection** [comment]
Good question. I honestly cannot remember why I did this. Could have been a
placeholder for figuring out how to get Giles to shutdown gracefully if a
build or test was running. Given that I cannot remember, and the feature
currently serves no useful purpose, I think it should be removed until I
figure out what I was thinking. :-)

On May 20, 2011 3:04 PM, "cbilson" <
reply@reply.github.com>
wrote:

It was a little disorienting when it didn't exit after I hit Ctrl-C.
Obviously this is intentional, but I was wondering what the reasoning behind
this was.

## 

Reply to this email directly or view it on GitHub:
https://github.com/codereflection/Giles/issues/4

**Comment by codereflection** [comment]
Fixed in next release of Giles...
